
task_params:
task: image_recognition
dataset: mnist

#training_params:
batch_size: 128
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
epochs: 350
optimizer: SGD
scheduler: True

#model_params:
architecture: simple
pretrained: True
resumed_model: False


#runner_params:
save_model: True
log: True
tb: False
random: False # fix random seed
save_on_epochs: []
log_interval: 10
device: cuda

#backdoor_params:
attack_type: blind # poison, trojaning?
poisoning_proportion: 0.5
poison_number: 8
single_pixel: False
backdoor: False
alpha: 0.95
scale_threshold: 0.01
mgda_mode: none

losses:
  - backdoor
  - normal
#  - nc_adv
#  - ewc
#  - latent
#  - latent_fixed

#losses_scales:
#  backdoor: 0.1
#  normal: 1
#  latent: 0.1
#  nc_adv: 0.1
#  latent_fixed: 0.2

